model: fasterrcnn_convnext_small
data_config: /srv/fasterrcnn_pytorch_api/data/submarine_det/brackish.yaml
use_train_aug: false
device: true
epochs: 20
workers: 4
batch: 4
lr: 0.001
imgsz: 640
vis_transformed: false
no_mosaic: true
SAVE_VALID_PREDICTION_IMAGES: false
cosine_annealing: true
weights: null
resume_training: false
square_training: false
seed: 0
name: /srv/fasterrcnn_pytorch_api/models/2023-05-10_121810
distributed: false
